<?php

namespace EasyTel\Types;

class Message
{
    public int $message_id;
    public int $message_thread_id;
    public User $from;
    public Chat $sender_chat;
    public int $sender_boost_count;
    public User $sender_business_bot;
    public int $date;
    public string $business_connection_id;
    public Chat $chat;
    public MessageOrigin $forward_origin;
    public True $is_topic_message;
    public True $is_automatic_forward;
    public Message $reply_to_message;
    public ExternalReplyInfo $external_reply;
    public TextQuote $quote;
    public Story $reply_to_story;
    public User $via_bot;
    public int $edit_date;
    public True $has_protected_content;
    public True $is_from_offline;
    public string $media_group_id;
    public string $author_signature;
    public string $text;
    public array  $entities;
    public LinkPreviewOptions $link_preview_options;
    public string $effect_id;
    public Animation $animation;
    public Audio $audio;
    public Document $document;
    public array  $photo;
    public Sticker $sticker;
    public Story $story;
    public Video $video;
    public VideoNote $video_note;
    public Voice $voice;
    public string $caption;
    public array  $caption_entities;
    public True $show_caption_above_media;
    public True $has_media_spoiler;
    public Contact $contact;
    public Dice $dice;
    public Game $game;
    public Poll $poll;
    public Venue $venue;
    public Location $location;
    public array  $new_chat_members;
    public User $left_chat_member;
    public string $new_chat_title;
    public array  $new_chat_photo;
    public True $delete_chat_photo;
    public True $group_chat_created;
    public True $supergroup_chat_created;
    public True $channel_chat_created;
    public MessageAutoDeleteTimerChanged $message_auto_delete_timer_changed;
    public int $migrate_to_chat_id;
    public int $migrate_from_chat_id;
    public MaybeInaccessibleMessage $pinned_message;
    public Invoice $invoice;
    public SuccessfulPayment $successful_payment;
    public UsersShared $users_shared;
    public ChatShared $chat_shared;
    public string $connected_website;
    public WriteAccessAllowed $write_access_allowed;
    public PassportData $passport_data;
    public ProximityAlertTriggered $proximity_alert_triggered;
    public ChatBoostAdded $boost_added;
    public ChatBackground $chat_background_set;
    public ForumTopicCreated $forum_topic_created;
    public ForumTopicEdited $forum_topic_edited;
    public ForumTopicClosed $forum_topic_closed;
    public ForumTopicReopened $forum_topic_reopened;
    public GeneralForumTopicHidden $general_forum_topic_hidden;
    public GeneralForumTopicUnhidden $general_forum_topic_unhidden;
    public GiveawayCreated $giveaway_created;
    public Giveaway $giveaway;
    public GiveawayWinners $giveaway_winners;
    public GiveawayCompleted $giveaway_completed;
    public VideoChatScheduled $video_chat_scheduled;
    public VideoChatStarted $video_chat_started;
    public VideoChatEnded $video_chat_ended;
    public VideoChatParticipantsInvited $video_chat_participants_invited;
    public WebAppData $web_app_data;
    public InlineKeyboardMarkup $reply_markup;
    
    public function __construct(array $update)
    {
        $objects = array_keys($update);
        $r = new \ReflectionClass(static::class);
        foreach ($objects as $object):
            if ($r->hasProperty($object)):
                $prop = $r->getProperty($object);
                $type = $prop->getType();
                if (in_array($type, ['mixed', 'True', 'string', 'bool', 'int', 'float', 'array'])) $this->{$object} = $update[$object];
            endif;
        endforeach;
        if (isset($update['from'])) $this->from = new User($update['from']);
        if (isset($update['sender_chat'])) $this->sender_chat = new Chat($update['sender_chat']);
        if (isset($update['sender_business_bot'])) $this->sender_business_bot = new User($update['sender_business_bot']);
        if (isset($update['chat'])) $this->chat = new Chat($update['chat']);
        if (isset($update['forward_origin'])) $this->forward_origin = new MessageOrigin($update['forward_origin']);
        if (isset($update['reply_to_message'])) $this->reply_to_message = new Message($update['reply_to_message']);
        if (isset($update['external_reply'])) $this->external_reply = new ExternalReplyInfo($update['external_reply']);
        if (isset($update['quote'])) $this->quote = new TextQuote($update['quote']);
        if (isset($update['reply_to_story'])) $this->reply_to_story = new Story($update['reply_to_story']);
        if (isset($update['via_bot'])) $this->via_bot = new User($update['via_bot']);
        if (isset($update['link_preview_options'])) $this->link_preview_options = new LinkPreviewOptions($update['link_preview_options']);
        if (isset($update['animation'])) $this->animation = new Animation($update['animation']);
        if (isset($update['audio'])) $this->audio = new Audio($update['audio']);
        if (isset($update['document'])) $this->document = new Document($update['document']);
        if (isset($update['sticker'])) $this->sticker = new Sticker($update['sticker']);
        if (isset($update['story'])) $this->story = new Story($update['story']);
        if (isset($update['video'])) $this->video = new Video($update['video']);
        if (isset($update['video_note'])) $this->video_note = new VideoNote($update['video_note']);
        if (isset($update['voice'])) $this->voice = new Voice($update['voice']);
        if (isset($update['contact'])) $this->contact = new Contact($update['contact']);
        if (isset($update['dice'])) $this->dice = new Dice($update['dice']);
        if (isset($update['game'])) $this->game = new Game($update['game']);
        if (isset($update['poll'])) $this->poll = new Poll($update['poll']);
        if (isset($update['venue'])) $this->venue = new Venue($update['venue']);
        if (isset($update['location'])) $this->location = new Location($update['location']);
        if (isset($update['left_chat_member'])) $this->left_chat_member = new User($update['left_chat_member']);
        if (isset($update['message_auto_delete_timer_changed'])) $this->message_auto_delete_timer_changed = new MessageAutoDeleteTimerChanged($update['message_auto_delete_timer_changed']);
        if (isset($update['pinned_message'])) $this->pinned_message = new MaybeInaccessibleMessage($update['pinned_message']);
        if (isset($update['invoice'])) $this->invoice = new Invoice($update['invoice']);
        if (isset($update['successful_payment'])) $this->successful_payment = new SuccessfulPayment($update['successful_payment']);
        if (isset($update['users_shared'])) $this->users_shared = new UsersShared($update['users_shared']);
        if (isset($update['chat_shared'])) $this->chat_shared = new ChatShared($update['chat_shared']);
        if (isset($update['write_access_allowed'])) $this->write_access_allowed = new WriteAccessAllowed($update['write_access_allowed']);
        if (isset($update['passport_data'])) $this->passport_data = new PassportData($update['passport_data']);
        if (isset($update['proximity_alert_triggered'])) $this->proximity_alert_triggered = new ProximityAlertTriggered($update['proximity_alert_triggered']);
        if (isset($update['boost_added'])) $this->boost_added = new ChatBoostAdded($update['boost_added']);
        if (isset($update['chat_background_set'])) $this->chat_background_set = new ChatBackground($update['chat_background_set']);
        if (isset($update['forum_topic_created'])) $this->forum_topic_created = new ForumTopicCreated($update['forum_topic_created']);
        if (isset($update['forum_topic_edited'])) $this->forum_topic_edited = new ForumTopicEdited($update['forum_topic_edited']);
        if (isset($update['forum_topic_closed'])) $this->forum_topic_closed = new ForumTopicClosed($update['forum_topic_closed']);
        if (isset($update['forum_topic_reopened'])) $this->forum_topic_reopened = new ForumTopicReopened($update['forum_topic_reopened']);
        if (isset($update['general_forum_topic_hidden'])) $this->general_forum_topic_hidden = new GeneralForumTopicHidden($update['general_forum_topic_hidden']);
        if (isset($update['general_forum_topic_unhidden'])) $this->general_forum_topic_unhidden = new GeneralForumTopicUnhidden($update['general_forum_topic_unhidden']);
        if (isset($update['giveaway_created'])) $this->giveaway_created = new GiveawayCreated($update['giveaway_created']);
        if (isset($update['giveaway'])) $this->giveaway = new Giveaway($update['giveaway']);
        if (isset($update['giveaway_winners'])) $this->giveaway_winners = new GiveawayWinners($update['giveaway_winners']);
        if (isset($update['giveaway_completed'])) $this->giveaway_completed = new GiveawayCompleted($update['giveaway_completed']);
        if (isset($update['video_chat_scheduled'])) $this->video_chat_scheduled = new VideoChatScheduled($update['video_chat_scheduled']);
        if (isset($update['video_chat_started'])) $this->video_chat_started = new VideoChatStarted($update['video_chat_started']);
        if (isset($update['video_chat_ended'])) $this->video_chat_ended = new VideoChatEnded($update['video_chat_ended']);
        if (isset($update['video_chat_participants_invited'])) $this->video_chat_participants_invited = new VideoChatParticipantsInvited($update['video_chat_participants_invited']);
        if (isset($update['web_app_data'])) $this->web_app_data = new WebAppData($update['web_app_data']);
        if (isset($update['reply_markup'])) $this->reply_markup = new InlineKeyboardMarkup($update['reply_markup']);
    }
}